databases:
  - name: membersonly
    databaseName: membersonlydb
    user: membersonly

services:
  - type: web
    name: members-only
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: membersonlydb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
